version: "3.8"

services:
  fill-mask:
    build:
      dockerfile: FillMask-Dockerfile
    ports:
      - "8081:8081"
  lang-detec:
    build:
      dockerfile: LangDetec-Dockerfile
    ports:
      - "8082:8082"